Test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', TemplateView.as_view(template_name='base.html'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('complaints/', include(('complaints.urls', 'complaints'), namespace='complaints'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views


urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('settings/<int:pk>', views.AccountSettings.as_view(), name='settings'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
]

complaints/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register('complaints', views.ComplaintView)


urlpatterns = [
    path('my_complaints/', views.ComplaintList.as_view(), name='my_complaints'),
    path('api/', include(router.urls)),
    path('new/', views.RegisterComplaint.as_view(), name='new_complain'),
    path('detail/<int:pk>', views.DetailComplaints.as_view(), name='detail_complain'),
    path('', views.ListComplaints.as_view(), name='all_complain'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class User(AbstractUser):
    profile_image = models.ImageField(upload_to='profile_pics', default='1.png')
    phone_no = models.CharField(max_length=10, default=00000)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)


    def get_absolute_url(self):
        return reverse('accounts:dashboard')

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from . models import User
from django import forms


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'bio', 'location', 'phone_no', 'profile_image']

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from . models import User
from django.views.generic import CreateView, UpdateView, FormView, DetailView, View
from . forms import RegisterForm
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages


class Register(FormView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(reverse('accounts:dashboard'))



def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))

            else:
                return HttpResponse('<h2> Account Not Active </h2>')

        else:
            print('Someone tried to login failed on our site.')
            return HttpResponse('<h2>Invalid login credentials applied </h2>')

    else:
        return render(request, 'accounts/login.html', {})


class AccountSettings(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ['username', 'first_name', 'last_name', 'email', 'bio', 'location', 'phone_no', 'profile_image']
    template_name_suffix = '_update_form'

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, 'Your Account Settings were updated successfully!')
        return reverse('accounts:dashboard')


class Dashboard(LoginRequiredMixin, View):
    template_name = 'accounts/dashboard.html'

    def get(self, request, *args, **kwargs):
        user_object = User.objects.get(pk=request.user.id)
        return render(request, self.template_name, {'object': user_object})











templates/accounts/dashboard.html
<style>
    .profile-container {
        padding: 1rem;
        background-color: #306ccc;
        border-radius: 0.6rem;
        margin: 1rem;
        font-family: "Source Sans Pro", sans-serif;
        color: mintcream;
    }

    .biography {
        white-space: pre-line;
    }

    .section-heading {
        font-family: "Ubuntu", sans-serif;
        font-size: 1rem;
        color: antiquewhite;
    }

    .complain-container {
        width: 80%;
        background-color: mintcream;
        color: crimson;
    }

</style>
{% extends 'base.html' %}

{% block header %}
    <title>Crime Dashboard</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}

{% block content %}
    {% load widget_tweaks %}
    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}

    {% if messages %}
        {% for message in messages %}
            <div class="text-center alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}

   <div class="w-50 mx-auto my-3">
   <h4 class="text-center mx-auto my-3">Hello, {{ object.username }}! WELCOME TO YOUR DASHBOARD</h4>
   <div class="container profile-container">
        <div class="row justify-content-around">
            <div class="col-sm-4">
                <img src="{{ object.profile_image.url }}" alt="Image not available" height="200" width="250">
                <h5 class="text-center my-3">Profile Avatar</h5>
            </div>

            <div class="col-sm-6">
                <p class="section-heading">{{ object.username }}</p>
                <p> {{ object.bio }}</p>
                <p class="section-heading">Contact No</p> <p> {{ object.phone_no }}</p>
                <p class="section-heading">Email</p><p> {{ object.email }}</p>

            </div>
        </div>

   </div>

    <div class="container">
        <div class="container row complain-container">

        </div>
    </div>

    <div class="container my-3 mx-auto text-center">
        <button class="btn btn-danger" id="show_complain">My Complaints</button>
        <button class="btn btn-primary" id="complain">Register a new Complaint</button>
    </div>

    <script>

    $(document).ready(function() {
       console.log('Loaded!!');

       $('#complain').click(function() {
           console.log($(this).text());
           document.location.href = "{% url 'complaints:new_complain' %}"
       });

       $('#show_complain').click(function() {
          let box = $('.complain-container');
          box.empty();
          box.hide();
          $.ajax({

            url: '{% url 'complaints:my_complaints' %}',
            type: 'GET',
            cache: false,
            success: function(data){
                if(data.length > 0)
                {
                   let pre = `<div class="col-sm-3 my-3">
                                <h4 class="text-center">Title</h4>
                               </div>

                              <div class="col-sm-6 my-3">
                                <h4 class="text-center">Description</h4>
                              </div>

                              <div class="col-sm-3 my-3">
                                <h4 class="text-center">Posted At</h4>
                              </div>`;
                   box.append(pre);
                   for(let i=0; i<data.length; i++)
                    {
                        box.append('<div class="col-sm-3 my-2">' + data[i].title + '</div>');
                        box.append('<div class="col-sm-6 my-2">' + data[i].description + '</div>');
                        box.append('<div class="col-sm-3 my-2">' + data[i].created_at + '</div>');
                    }
                    box.fadeIn(1000);
                }

		    },
		    error: function(XMLHttpRequest, textStatus, errorThrown) {
                alert("some error");
            }
          });
       })
    });

    </script>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block header %}
    <title>User Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}

{% block content %}
    {% load widget_tweaks %}
    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}

   <div class="w-50 mx-auto my-3">
   <h4 class="text-center mx-auto my-3">User Login</h4>
        <form method="post" action="{% url 'accounts:login' %}">
              {% csrf_token %}

              <div class="form-group">
                  <label for="username">Username:</label>
                  <input class="form-control" type="text" name="username" placeholder="Username">
              </div>

              <div class="form-group">
                  <label for="password">Password</label>
                  <input class="form-control" type="password" name="password" placeholder="Your Password">
              </div>

              <div class="container text-center">
                  <input type="submit" class="btn btn-danger col-md-4" name="" value="Login">
                  <button class="btn btn-success col-md-4"><a href="{% url 'accounts:register' %}" class="text-white">Register</a></button>
              </div>

        </form>
    </div>

{% endblock %}

templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block header %} <title>User Registration</title>
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}



{% block content %}
    <div class="container w-50 mx-auto my-3">
        <h4 class="text-center">REGISTRATION FORM</h4>
        <form enctype="multipart/form-data" method="post">{% csrf_token %}
        {% load widget_tweaks %}

        {% if messages %}
            {% for message in messages %}
                <div class="alert-danger">{{ message }}</div>
            {% endfor %}
        {% endif %}

        <div class="form-group">
            <label for="{{ form.username_for_label }}">Choose Your Username:</label>
            {{ form.username|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.first_name_for_label }}">Your First Name:</label>
            {{ form.first_name|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.last_name_for_label }}">Your Last Name:</label>
            {{ form.last_name|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.email_for_label }}">Your Email:</label>
            {{ form.email|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.password1_for_label }}">Your Password:</label>
            {{ form.password1|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.password2_for_label }}">Confirm Your Password:</label>
            {{ form.password2|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.bio_for_label }}">Your Biography in Short:</label>
            {{ form.bio|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.profile_image_for_label }}">Upload Your Profile Picture:</label>
            {{ form.profile_image|add_class:"form-file-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.phone_no_for_label }}">Your Phone Number:</label>
            {{ form.phone_no|add_class:"form-control" }}
        </div>

        <div class="container text-center w-50">
            <input type="submit" class="btn-lg btn-success" value="REGISTER">
        </div>

    </form>
</div>
{% endblock %}

templates/accounts/user_update_form.html

{% extends 'base.html' %}
{% load static %}

{% block header %} <title>Update Registration</title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}

{% block content %}
    <div class="container w-50 mx-auto my-3">
        <h4 class="text-center">ACCOUNT SETTINGS</h4>
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            <form enctype="multipart/form-data" method="post">{% csrf_token %}
        {% load widget_tweaks %}

        {% if messages %}
            {% for message in messages %}
                <div class="alert-danger">{{ message }}</div>
            {% endfor %}
        {% endif %}

        <div class="form-group">
            <label for="{{ form.username_for_label }}">Choose Your Username:</label>
            {{ form.username|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.first_name_for_label }}">Your First Name:</label>
            {{ form.first_name|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.last_name_for_label }}">Your Last Name:</label>
            {{ form.last_name|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.email_for_label }}">Your Email:</label>
            {{ form.email|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.bio_for_label }}">Your Biography in Short:</label>
            {{ form.bio|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.profile_image_for_label }}">Upload Your Profile Picture:</label>
            {{ form.profile_image|add_class:"form-file-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.phone_no_for_label }}">Your Phone Number:</label>
            {{ form.phone_no|add_class:"form-control" }}
        </div>

        <div class="container text-center w-50">
            <input type="submit" class="btn-lg btn-secondary" value="UPDATE SETTINGS">
        </div>

    </form>
        </form>
    </div>
{% endblock %}