Test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', TemplateView.as_view(template_name='base.html'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('complaints/', include(('complaints.urls', 'complaints'), namespace='complaints'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views


urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('settings/<int:pk>', views.AccountSettings.as_view(), name='settings'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block header %}
        <title>Crime Reporting System</title>
    {% endblock %}

{% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Nunito|PT+Sans+Narrow|Source+Sans+Pro|Ubuntu" rel="stylesheet">
    <style>
        .navbar-brand {
            font-family: "PT Sans Narrow", sans-serif;
            font-size: 2rem;
            color: red;
            letter-spacing: 0.3rem;
        }

        .nav-link {
            font-family: "Nunito", sans-serif;
            font-size: 1.2rem;
            color: coral;
        }

        .header {
            color: darkorange;
            font-family: "Nunito", sans-serif;
            font-size: 2rem;
            padding: 1.5rem;
            margin: 1rem;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-md bg-primary">
  <!-- Brand -->
  <a class="navbar-brand text-white" href="#" >ONLINE CRIME REPORTING WEBSITE</a>

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
    <ul class="navbar-nav">
      {% if request.user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'accounts:dashboard' %}">Dashboard</a>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white" href="#">Hello {{ request.user }}</a>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'accounts:settings' pk=request.user.id %}">Profile Settings</a>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'accounts:logout' %}">Log Out</a>
          </li>
      {% else %}
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'accounts:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'accounts:register' %}">Register</a>
          </li>
      {% endif %}
    </ul>
  </div>
</nav>

{% block content %}
   <p class="header text-center">
    <a href="/" class="d-block mb-4"><img style="height: 1000px;"  src="{% static 'crime3.webp' %}" alt=""></a>
  
   </p>

{% endblock %}

</body>
</html>
