Test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', TemplateView.as_view(template_name='base.html'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('complaints/', include(('complaints.urls', 'complaints'), namespace='complaints'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

complaints/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register('complaints', views.ComplaintView)


urlpatterns = [
    path('my_complaints/', views.ComplaintList.as_view(), name='my_complaints'),
    path('api/', include(router.urls)),
    path('new/', views.RegisterComplaint.as_view(), name='new_complain'),
    path('detail/<int:pk>', views.DetailComplaints.as_view(), name='detail_complain'),
    path('', views.ListComplaints.as_view(), name='all_complain'),
]

project/complaints/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register('complaints', views.ComplaintView)


urlpatterns = [
    path('my_complaints/', views.ComplaintList.as_view(), name='my_complaints'),
    path('api/', include(router.urls)),
    path('new/', views.RegisterComplaint.as_view(), name='new_complain'),
    path('detail/<int:pk>', views.DetailComplaints.as_view(), name='detail_complain'),
    path('', views.ListComplaints.as_view(), name='all_complain'),
]

complaints/models.py
from django.db import models
from . choices import CRIME_CATEGORY
from django.urls import reverse
from Test import settings
from django.template.defaultfilters import slugify


class Complaint(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    seen_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='supervisor', on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=100)
    category = models.IntegerField(choices=CRIME_CATEGORY, default=1)
    description = models.TextField(max_length=200)
    location = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('accounts:dashboard')

    def __str__(self):
        return self.title

project/complaints/models.py
from django.db import models
from . choices import CRIME_CATEGORY
from django.urls import reverse
from Test import settings
from django.template.defaultfilters import slugify


class Complaint(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    seen_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='supervisor', on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=100)
    category = models.IntegerField(choices=CRIME_CATEGORY, default=1)
    description = models.TextField(max_length=200)
    location = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('accounts:dashboard')

    def __str__(self):
        return self.title

complaints/forms.py
from . models import Complaint
from django import forms


class ComplainForm(forms.ModelForm):

    class Meta:
        model = Complaint
        fields = ['title', 'category', 'description', 'location']

project/complaints/forms.py
from . models import Complaint
from django import forms


class ComplainForm(forms.ModelForm):

    class Meta:
        model = Complaint
        fields = ['title', 'category', 'description', 'location']

complaints/views.py
from django.shortcuts import render
from . forms import ComplainForm
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from . models import Complaint
from django.views.generic import CreateView, FormView, ListView, DetailView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from . serializers import ComplaintSerializer
from rest_framework import viewsets, permissions, generics
from rest_framework.response import Response


class RegisterComplaint(SuccessMessageMixin, CreateView):
    form_class = ComplainForm
    template_name = 'complaints/new_complaint.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.seen_by = None
        form.save()

        messages.success(self.request,
                         'Your complaint was registered successfully, one of our correspondents would soon get back to you')

        return HttpResponseRedirect(reverse('accounts:dashboard'))


class ListComplaints(ListView):
    model = Complaint
    template_name = 'complaints/all_complaints.html'


class DetailComplaints(DetailView):
    model = Complaint
    template_name = 'complaints/complaints_detail.html'

    def update_seen_by(self):
        self.object.seen_by = self.request.user
        print(str(self.object))




class ComplaintView(viewsets.ModelViewSet):
    queryset = Complaint.objects.all()
    serializer_class = ComplaintSerializer

    permission_classes = (permissions.AllowAny,)

    def post(self, request, format=None):
        return Response("ok")


class ComplaintList(generics.ListAPIView):
    serializer_class = ComplaintSerializer


    def get_queryset(self):
        user = self.request.user
        return Complaint.objects.filter(created_by=user)

project/complaints/views.py
from django.shortcuts import render
from . forms import ComplainForm
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from . models import Complaint
from django.views.generic import CreateView, FormView, ListView, DetailView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from . serializers import ComplaintSerializer
from rest_framework import viewsets, permissions, generics
from rest_framework.response import Response


class RegisterComplaint(SuccessMessageMixin, CreateView):
    form_class = ComplainForm
    template_name = 'complaints/new_complaint.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.seen_by = None
        form.save()

        messages.success(self.request,
                         'Your complaint was registered successfully, one of our correspondents would soon get back to you')

        return HttpResponseRedirect(reverse('accounts:dashboard'))


class ListComplaints(ListView):
    model = Complaint
    template_name = 'complaints/all_complaints.html'


class DetailComplaints(DetailView):
    model = Complaint
    template_name = 'complaints/complaints_detail.html'

    def update_seen_by(self):
        self.object.seen_by = self.request.user
        print(str(self.object))




class ComplaintView(viewsets.ModelViewSet):
    queryset = Complaint.objects.all()
    serializer_class = ComplaintSerializer

    permission_classes = (permissions.AllowAny,)

    def post(self, request, format=None):
        return Response("ok")


class ComplaintList(generics.ListAPIView):
    serializer_class = ComplaintSerializer


    def get_queryset(self):
        user = self.request.user
        return Complaint.objects.filter(created_by=user)

templates/complaints/all_complaints.html
<style>
    .complain-container {
        font-family: "Nunito", sans-serif;
        padding: 1rem;
        margin: 1rem;
    }
</style>

{% extends 'base.html' %}
{% load static %}

{% block header %} <title>All Registered Complaints</title>

{% endblock %}

{% block content %}
    <div class="container complain-container">
        <table class="table">
    <thead>
      <tr class="my-3">
        <th>Complain Title</th>
        <th>Submitted By</th>
        <th>View Details</th>
      </tr>
    </thead>
    <tbody>
    {% for each_object in object_list %}
        <tr>
            <td>{{ each_object.title }}</td>
            <td>{{ each_object.created_by }}</td>
            <td><a href="{% url 'complaints:detail_complain' pk=each_object.pk %}">View Details</a></td>
        </tr>
    {% endfor %}

    </tbody>
  </table>
    </div>
{% endblock %}

templates/complaints/api_complaint_list.html
<style>
    .complain-container {
        font-family: "Nunito", sans-serif;
        padding: 1rem;
        margin: 1rem;
    }
</style>

{% extends 'base.html' %}
{% load static %}

{% block header %} <title>All Registered Complaints</title>

{% endblock %}

{% block content %}
    {{ object_list }}
{% endblock %}

templates/complaints/complaints_detail.html
<style>
    .detail-container {
        font-family: "Nunito", sans-serif;
        color: crimson;
        font-weight: 500;
        font-size: 1.2rem;
    }

    .detail-container {
        position: relative;

    }

    .fa {
        font-size: 40px;
        color: mintcream;
    }

    .fa:hover {
        cursor: hand;
    }

    #form-container {
        position: absolute;
        margin: 1.5rem;
        background-color: #8eaf5b;
        width: 80%;
        top: 50px;
        left: 100px;
        z-index: 10;
        border-radius: 0.6rem;

    }
</style>

{% extends 'base.html' %}

{% block header %}
    <title>Complain Detail</title>
    {% load static %}
{% endblock %}

{% block content %}
    <div class="container detail-container mx-auto my-3">

        <div class="card">
          <div class="card-header text-center">{{ object.title }}</div>
          <div class="card-body">
            <div class="container text-center">
                <p>Complaint Posted By : {{ object.created_by }}</p>
                <p>Location : {{ object.location }}</p>
                <p>Time : {{ object.created_at }}</p>
            </div>

            <div class="container bg-warning rounded p-2">
                <p>{{ object.description }}</p>
            </div>
          </div>

          <div class="card-footer">
              <div class="container text-center">
                  <button class="btn btn-primary" id="mail_btn">Mail Action Report to {{ object.created_by }}</button>
              </div>
          </div>
        </div>


    <div class="container card-body" id="form-container">
        <div class="container justify-content-between">
                <i class="fa fa-close" style="font-size:40px"></i></div>
            <h4 class="text-center mx-auto my-3">SEND EMAIL REPORT</h4>
            <form method="post" action="#">
              {% csrf_token %}

              <div class="form-group">
                  <label for="sender_email">SEND TO</label>
                  <input class="form-control" type="text" name="sender_email" id="sender_email" placeholder="Sender Email!">
              </div>

              <div class="form-group">
                  <label for="msg_subject">SUBJECT</label>
                  <input class="form-control" type="text" name="msg_subject" id="msg_subject" placeholder="Email Subject">
              </div>

              <div class="form-group">
                  <label for="msg_body">BODY</label>
                  <textarea class="form-control" rows="10" name="msg_body" id="msg_body" placeholder="Enter the body of Email"></textarea>

              </div>

              <div class="container text-center">
                  <button type="submit" class="btn btn-warning col-md-4" id="email_button" name="" value="Email Report">Email Report</button>
              </div>

        </form>
        </div>

    </div>

    <script>
    $(document).ready(function() {
       console.log('Loaded document');

       let form_container = $('#form-container');
       form_container.hide();
       // form_container.fadeIn(1000);

       $('#mail_btn').click(function() {
            form_container.fadeIn(500);
       });

       $('.fa-close').click(function() {
            form_container.fadeOut(500);
       });
    });


    </script>
{% endblock %}

templates/complaints/new_complaint.html
{% extends 'base.html' %}
{% load static %}

{% block header %} <title>Register a New Complaint</title>
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}

{% block content %}
    <div class="container w-50 mx-auto my-3">
        <h4 class="text-center">COMPLAINTS FORM</h4>
        <form enctype="multipart/form-data" method="post">{% csrf_token %}
        {% load widget_tweaks %}

        {% if messages %}
            {% for message in messages %}
                <div class="alert-danger">{{ message }}</div>
            {% endfor %}
        {% endif %}

        <div class="form-group">
            <label for="{{ form.title_for_label }}">Complaint Title</label>
            {{ form.title|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.category_for_label }}">Category of Incident</label>
            {{ form.category|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.description_for_label }}">Please Describe What Happened With You?</label>
            {{ form.description|add_class:"form-control" }}
        </div>

        <div class="form-group">
            <label for="{{ form.location_for_label }}">Where did this happen?:</label>
            {{ form.location|add_class:"form-control" }}
        </div>

        <div class="container text-center w-50">
            <input type="submit" class="btn-lg btn-success" value="POST COMPLAIN">
        </div>

    </form>
</div>

    <script>
    $(document).ready(function() {
        let form_container = $('.container');
        form_container.hide();

        form_container.fadeIn(1000);
    });
    </script>
{% endblock %}